# Pre-commit configuration file
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # Pyink - Google's Python formatter (fork of Black)
  - repo: https://github.com/google/pyink
    rev: '24.10.1'  # Use the latest stable version
    hooks:
      - id: pyink
        name: pyink
        description: "Format Python code with pyink"
        entry: pyink
        language: python
        types: [python]
        args: [--line-length=88]

  # Pylint - Python static code analysis
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        description: "Check Python code with pylint"
        entry: pylint
        language: python
        types: [python]
        args: [
          --rcfile=.pylintrc,
          --score=no,
          --reports=no,
          --output-format=colorized
        ]
        additional_dependencies: [pylint]

  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        description: "Trim trailing whitespace"
      - id: end-of-file-fixer
        description: "Ensure files end with a newline"
      - id: check-yaml
        description: "Check YAML files for syntax errors"
      - id: check-toml
        description: "Check TOML files for syntax errors"
      - id: check-merge-conflict
        description: "Check for merge conflict markers"
      - id: check-added-large-files
        description: "Prevent large files from being committed"
        args: ['--maxkb=500']

# Global settings
default_stages: [commit]
fail_fast: false
